# Generated by Django 5.0.6 on 2024-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomesource",
            old_name="data",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="transactions",
            old_name="data",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="expenses",
            name="data",
        ),
        migrations.RemoveField(
            model_name="expenses",
            name="description",
        ),
        migrations.RemoveField(
            model_name="expenses",
            name="name",
        ),
        migrations.RemoveField(
            model_name="incomesource",
            name="name",
        ),
        migrations.AddField(
            model_name="expenses",
            name="category",
            field=models.CharField(default="Default Category", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incomesource",
            name="description",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
